"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory$all$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[battery]
disabled = false
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = ".../"

[time]
disabled = false
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"

[git_branch]
symbol = "🌱 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"